[FIX] runbot_send_email: email is required for find_or_create partner
Fix error:

```bash
  File "runbot_send_email/models/runbot_build.py", line 200, in send_
email
    partner_id = partner_obj.find_or_create(email_to)
  File "openerp/addons/base/res/res_partner.py", line 677, in find_or_create
    assert email, 'an email is required for find_or_create to work'
AssertionError: an email is required for find_or_create to work
```